# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antithesis < Formula
  desc "A platform for building the impossible."
  homepage "https://antithesis.com"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.8/antithesis_0.0.8_darwin_amd64.tar.gz"
      sha256 "3e2a0256adb92bedf58733aa9d1df502d1e4fbaa0a6b27df995b8c7c4f329fe4"

      def install
        bin.install "antithesis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.8/antithesis_0.0.8_darwin_arm64.tar.gz"
      sha256 "404a32f6eff924f5b3a56c5a9120099720e4e294856b2d9d4be6b5a1de6dc05b"

      def install
        bin.install "antithesis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.8/antithesis_0.0.8_linux_amd64.tar.gz"
        sha256 "a51fb1d8b97aab8c1754feb2a3d4224723cab742fbb587cb6cab3a1d44e80152"

        def install
          bin.install "antithesis"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.8/antithesis_0.0.8_linux_arm64.tar.gz"
        sha256 "bbc3ff6209a097df3fa98471bcc5102951ed37be96e60412c7fa6eb95038b677"

        def install
          bin.install "antithesis"
        end
      end
    end
  end

  test do
    system "#{bin}/antithesis", "--version"
  end
end
