# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antithesis < Formula
  desc "A platform for building the impossible."
  homepage "https://antithesis.com"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.10/antithesis_0.0.10_darwin_amd64.tar.gz"
      sha256 "80c1b5f610acb22a5d141d1c0d08ad128131af78d79c8c531aeb030ea5fe07b0"

      def install
        bin.install "antithesis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.10/antithesis_0.0.10_darwin_arm64.tar.gz"
      sha256 "6e72d3c340b1b5e93bb8424d471a3f08f5e8fbacab593708fca2046c030d8acb"

      def install
        bin.install "antithesis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.10/antithesis_0.0.10_linux_amd64.tar.gz"
        sha256 "5a7b20046e8bddcbe62cfb696da560a43ba0f16af34ecb19d38d4ab61a487091"

        def install
          bin.install "antithesis"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.10/antithesis_0.0.10_linux_arm64.tar.gz"
        sha256 "81ddad9e90f22f6f156bc9bf0259742be36be5dd2304babeb771e6a043d33560"

        def install
          bin.install "antithesis"
        end
      end
    end
  end

  test do
    system "#{bin}/antithesis", "--version"
  end
end
