# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antithesis < Formula
  desc "A platform for building the impossible."
  homepage "https://antithesis.com"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.6/antithesis_0.0.6_darwin_amd64.tar.gz"
      sha256 "57a9e8081e8a07934caba2af44660dbc3423f22b39d365a4e8d41e06202514f9"

      def install
        bin.install "antithesis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.6/antithesis_0.0.6_darwin_arm64.tar.gz"
      sha256 "0426c4a6dcb8bce5375df10827adf105c254a0eb224f06c3aab6f4ea19fa3772"

      def install
        bin.install "antithesis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.6/antithesis_0.0.6_linux_amd64.tar.gz"
        sha256 "d471d42fb2007131d30934257dbc37f35367e13cd160f617dd66feffed5a79db"

        def install
          bin.install "antithesis"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guergabo/antithesis-cli/releases/download/v0.0.6/antithesis_0.0.6_linux_arm64.tar.gz"
        sha256 "741e66e7ec55ac9dc2240ae31ee9e7f32514ad31186e50d18f5feea61344cfda"

        def install
          bin.install "antithesis"
        end
      end
    end
  end

  test do
    system "#{bin}/antithesis", "--version"
  end
end
