name: Tag and Release on Merge
on:
  pull_request:
    types: [merged]
    branches:
      - main

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag and release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.head_ref }}
          tag_name: ${{ github.head_ref }}
          body: |
            Release created automatically from merged branch ${{ github.head_ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
