name: Tag and Release on Merge
on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  create-tag-and-release:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag and release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.head_ref }}
          tag_name: ${{ github.head_ref }}
          body: |
            Release created automatically from merged branch ${{ github.head_ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
